### ISSUE TITLE
Access host at a given port

### ISSUE THREAD

**Issue by karbica** [blueimp/nightwatch#13]
Hello,

I'm trying to configure the nightwatch file and docker-compose file to run against a server on the host.

For example, I'm serving up the site at `localhost:4444` on my machine and I would like nightwatch to use that instead of the `http://nginx` URL.

I have tried exposing ports configuring networks but to no avail. How would I go about this?

**Comment by blueimp** [comment]
This depends on your operating system and the docker network mode used.
With the default bridge network and on MacOS, see. e.g.:
https://docs.docker.com/docker-for-mac/networking/#per-container-ip-addressing-is-not-possible

Since this doesn't really have anything to do with this project, I'm closing this issue.
