### ISSUE TITLE
Setting up multiple devices

### ISSUE THREAD

**Issue by ujwaldhakal** [blueimp/nightwatch#15]
Currently the tests run on chrome driver so is it possible to make different device configuration like android,firefox,ios to test further more?

**Comment by blueimp** [comment]
Since this project makes use of Docker, my reply is scoped to Docker-based solutions.

Firefox support depends on Webdriver support in Nightwatch.js, see also this issue here:
https://github.com/nightwatchjs/nightwatch/issues/1285
From what I've read, proper Webdriver support is coming in Nightwatch 1.0.

Android support might be possible wrapping an emulator inside of a Dockerfile, thought that might be very slow.

iOS support is so far impossible since there's no way to run iOS inside of a Docker container.
